name: Link Branch to Issue
description: Links the branch to the specified issue by adding a comment.

inputs:
  github_token:
    description: GitHub token
    required: true
  issue_number:
    description: Issue number to link to the branch
    required: true

runs:
  using: composite
  steps:
    - name: Add branch link comment
      shell: bash
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ inputs.github_token }}" \
        https://api.github.com/repos/${{ github.repository }}/issues/${{ inputs.issue_number }}/comments \
        -d '{"body": "🔗 Linked branch: `${{ github.ref_name }}`"}'
