name: Assign Issue to User
description: Assigns an issue to the creator of the branch or PR

inputs:
  github_token:
    description: GitHub token
    required: true
  issue_number:
    description: Number of the issue to assign
    required: true

runs:
  using: composite
  steps:
    - name: Assign issue
      shell: bash
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ inputs.github_token }}" \
        https://api.github.com/repos/${{ github.repository }}/issues/${{ inputs.issue_number }}/assignees \
        -d '{"assignees":["${{ github.actor }}"]}'