name: Link PR to issue
on:
  pull_request:
    types: [opened]

jobs:
  link-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # ✅ Ensure local actions are available

      - name: Extract Issue Number from Branch Name
        id: extract-issue
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          ISSUE_NUMBER=$(echo "$BRANCH_NAME" | grep -oE '#[0-9]+' | tr -d '#')

          if [[ -z "$ISSUE_NUMBER" ]]; then
            echo "No issue number found, skipping."
            exit 0
          fi

          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Link Branch to GitHub Issue
        if: env.ISSUE_NUMBER != ''
        run: |
          ISSUE_NUMBER=${{ env.ISSUE_NUMBER }}
          BRANCH_NAME="${{ github.ref_name }}"
          REPO="${{ github.repository }}"

          COMMENT_BODY="🚀 A new branch [\`$BRANCH_NAME\`](https://github.com/$REPO/tree/$BRANCH_NAME) has been created for this issue."

          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/comments \
            -d "{\"body\": \"$COMMENT_BODY\"}"
  # link-pr:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Link PR to GitHub Issue
  #       if: github.event_name == 'pull_request'
  #       run: |
  #         PR_NUMBER=${{ github.event.pull_request.number }}
  #         ISSUE_NUMBER=$(echo "${{ github.event.pull_request.head.ref }}" | grep -oE '#[0-9]+' | tr -d '#')
  #         REPO="${{ github.repository }}"
  #         COMMENT_BODY="🚀 A new pull request [#${PR_NUMBER}](https://github.com/$REPO/pull/$PR_NUMBER) has been opened for this issue."

  #         curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
  #           -H "Accept: application/vnd.github.v3+json" \
  #           https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/comments \
  #           -d "{\"body\": \"$COMMENT_BODY\"}"