name: Link Branch to Issue
on:
  create:
    branches:
      - '*'

jobs:
  link-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 

      - name: Extract Issue Number
        uses: ./.github/actions/extract-issue  

      - name: Assign Issue to the Branch Creator
        if: env.ISSUE_NUMBER != ''
        uses: ./.github/actions/assign-issue
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Link Branch to Issue
      #   if: env.ISSUE_NUMBER != ''
      #   uses: ./.github/actions/link-branch
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Link Branch to Issue in Development Section
        if: env.ISSUE_NUMBER != ''
        run: |
          ISSUE_NUMBER=${{ env.ISSUE_NUMBER }}
          BRANCH_NAME="${{ github.ref_name }}"
          REPO="${{ github.repository }}"

          # Get the Issue ID using GraphQL
          ISSUE_ID=$(curl -s -X POST -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"query\": \"query { repository(owner: \\\"${REPO%/*}\\\", name: \\\"${REPO#*/}\\\") { issue(number: $ISSUE_NUMBER) { id } } }\"}" \
            https://api.github.com/graphql | jq -r '.data.repository.issue.id')

          if [[ "$ISSUE_ID" == "null" ]]; then
            echo "❌ Issue ID not found. Skipping..."
            exit 0
          fi

          # Link Branch to Issue in Development Section
          curl -X POST -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"query\": \"mutation { createLinkedBranch(input: {issueId: \\\"$ISSUE_ID\\\", name: \\\"$BRANCH_NAME\\\"}) { clientMutationId } }\"}" \
            https://api.github.com/graphql