name: Link Branch to Issue
on:
  create:
    branches:
      - '*'

jobs:
  link-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 

      - name: Extract Issue Number
        uses: ./.github/actions/extract-issue  

      # - name: Assign Issue to the Branch Creator
      #   if: env.ISSUE_NUMBER != ''
      #   uses: ./.github/actions/assign-issue
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Link Branch to Issue
      #   if: env.ISSUE_NUMBER != ''
      #   uses: ./.github/actions/link-branch
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract issue number from branch name
        id: extract
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          if [[ $BRANCH_NAME =~ issue-([0-9]+) ]]; then
            echo "ISSUE_NUMBER=${BASH_REMATCH[1]}" >> $GITHUB_ENV
          else
            echo "No issue number found in branch name. Skipping."
            exit 0
          fi

      - name: Get issue ID from GitHub API
        id: get-issue-id
        run: |
          ISSUE_NUMBER=${{ env.ISSUE_NUMBER }}
          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      -H "Content-Type: application/json" \
                      -d "{\"query\":\"query { repository(owner: \\\"OWNER\\\", name: \\\"REPO\\\") { issue(number: ${ISSUE_NUMBER}) { id } } }\"}" \
                      https://api.github.com/graphql)
          ISSUE_ID=$(echo $RESPONSE | jq -r '.data.repository.issue.id')
          if [[ "$ISSUE_ID" == "null" ]]; then
            echo "Issue ID not found. Skipping."
            exit 0
          fi
          echo "ISSUE_ID=$ISSUE_ID" >> $GITHUB_ENV

      - name: Get branch ID from GitHub API
        id: get-branch-id
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      -H "Content-Type: application/json" \
                      -d "{\"query\":\"query { repository(owner: \\\"OWNER\\\", name: \\\"REPO\\\") { ref(qualifiedName: \\\"refs/heads/${BRANCH_NAME}\\\") { id } } }\"}" \
                      https://api.github.com/graphql)
          BRANCH_ID=$(echo $RESPONSE | jq -r '.data.repository.ref.id')
          if [[ "$BRANCH_ID" == "null" ]]; then
            echo "Branch ID not found. Skipping."
            exit 0
          fi
          echo "BRANCH_ID=$BRANCH_ID" >> $GITHUB_ENV

      - name: Link branch to issue
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d "{\"query\":\"mutation LinkBranchToIssue($baseIssueId: ID!, $linkingIds: [ID!]!) { linkRepositoryLinkedBranch(input: {issueId: $baseIssueId, repositoryLinkedBranchIds: $linkingIds}) { clientMutationId } }\",\"variables\":{\"baseIssueId\":\"${{ env.ISSUE_ID }}\",\"linkingIds\":[\"${{ env.BRANCH_ID }}\"]}}" \
               https://api.github.com/graphql
