name: Link Branch to Issue
on:
  create:
    branches:
      - '*'

jobs:
  link-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 

      - name: Extract Issue Number
        uses: ./.github/actions/extract-issue  

      - name: Assign Issue to the Branch Creator
        if: env.ISSUE_NUMBER != ''
        uses: ./.github/actions/assign-issue
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Link Branch to Issue
        if: env.ISSUE_NUMBER != ''
        uses: ./.github/actions/link-branch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Link Branch to Issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          ISSUE_NUMBER="${{ env.ISSUE_NUMBER }}"
          BRANCH_NAME="${{ github.ref_name }}"
          REPO_URL="https://github.com/${{ github.repository }}"
          
          echo "Linking branch $BRANCH_NAME to issue #$ISSUE_NUMBER"

          curl -X POST -H "Authorization: Bearer $GH_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/timeline \
               -d "{\"event\": \"cross-referenced\", \"source\": {\"type\": \"branch\", \"branch\": {\"name\": \"$BRANCH_NAME\", \"repo\": \"$REPO\" }}}"