name: Link Branch to Issue

on:
  create:
    branches:
      - '*'

jobs:
  link-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Issue Number from Branch Name
        id: extract-issue
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          ISSUE_NUMBER=$(echo "$BRANCH_NAME" | grep -oE '#[0-9]+' | tr -d '#')

          if [[ -z "$ISSUE_NUMBER" ]]; then
            echo "No issue number found, skipping."
            exit 0
          fi

          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

      - name: Link Branch to GitHub Issue
        if: env.ISSUE_NUMBER != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER=${{ env.ISSUE_NUMBER }}
          BRANCH_NAME="${{ github.ref_name }}"
          REPO="${{ github.repository }}"

          COMMENT_BODY="🚀 A new branch \`$BRANCH_NAME\` has been created for this issue."

          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/comments \
            -d "{\"body\": \"$COMMENT_BODY\"}"
