name: Move Issue to In Review on PR

on:
  pull_request:
    types:
      - opened

jobs:
  move-issue-in-review:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Issue Number from Branch
        id: extract_issue
        run: |
          ISSUE_NUMBER=$(echo "${{ github.head_ref }}" | grep -oE '[0-9]+' | head -n1)
          if [ -z "$ISSUE_NUMBER" ]; then
            echo "No issue number found in branch name."
            exit 0
          fi
          echo "ISSUE_NUMBERr=$ISSUE_NUMBER" >> $GITHUB_OUTPUT

      - name: Move Issue to "In Review" Status
        if: env.ISSUE_NUMBER != ''
        uses: ./.github/actions/move-issue
        with:
          github_token: ${{ secrets.ORG_PROJECT_PAT }}
          org: 'Groupemtn'
          project_number: '16'
          status_name: 'In Review'
          issue_number: ${{ env.ISSUE_NUMBER }}
